# Site settings
title: Ciao
email: victor@ciaoapp.us
url: joinciao.com
description: "Join Ciao Now! Sign up for our waiting list!"
favicon: img/favicon.ico
# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5F87D7 #80B3FF
  secondary:  D60207 #FD6E8A
  secondary-dark: 534344 #A2122F
  link-color: BDAFAF
  alternate: fff

#scrollable sections 
learn-section-title: Learn More
work-section-title: How It Works
contact-section-title: Join The Waitlist

privacy-url: /privacy/

#hrefs
hrefs:
  first: page-top
  second: learn-more
  third: how-it-works  
  last: join-waitlist

#carousel background images
background:
  first: img/portfolio/bg1.jpg
  second: img/portfolio/bg2.jpg
  third: img/portfolio/bg3.jpg
  fourth: img/portfolio/bg.jpg

# Footer settings
footer:
  copyright: Ciao Inc. 
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ciaotelecom
  - title: facebook
    url: https://www.facebook.com/ciaotelecomglobal
  - title: linkedin
    url: https://www.linkedin.com/company/ciao-telecom-inc-
  - title: google-plus
    url: https://plus.google.com/+ciao/
  - title: github
    url: http://github.com/simonc312

# Postal address (add as many lines as necessary)
address:
  - line: 8390 Lyndon B Johnson Fwy
  - line: Dallas, TX 75243


# Handle Reading Markdown
markdown_ext: "markdown,mkdown,mkdn,md"

# Build settings
markdown: kramdown
permalink: pretty

defaults: 
  - scope:
      path: "privacy"
    values:
      layout: "default"
      type: "pages"
