# Site settings
title: Ciao App
email: simon@ciaotelecom.com
url: https://ciaoapp.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
favicon: img/favicon.ico
# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: AA9596 #80B3FF
  secondary:  D60207 #FD6E8A
  secondary-dark: FF8C1F #A2122F

#scrollable sections 
home-section-title: Learn More
work-section-title: How It Works
contact-section-title: Join Waitlist

#carousel background images
background:
  first: img/portfolio/bg1.jpg
  second: img/portfolio/bg2.jpg
  third: img/portfolio/bg3.jpg
  fourth: img/portfolio/bg.jpg
# Footer settings
footer:
  copyright: Ciao Inc. 
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ciaotelecom
  - title: facebook
    url: https://www.facebook.com/ciaotelecomglobal
  - title: linkedin
    url: https://www.linkedin.com/company/ciao-telecom-inc-
  - title: google-plus
    url: https://plus.google.com/+ciao/
  - title: github
    url: http://github.com/simonc312

# Postal address (add as many lines as necessary)
address:
  - line: 8390 Lyndon B Johnson Fwy
  - line: Dallas, TX 75243


# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
