# Site settings
title: Poptalk
email: care@poptalk.us
url: joinciao.com
description: "Join Poptalk Now! Download our app from the Google Play Store!"
favicon: img/favicon.ico
# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffffff #80B3FF
  secondary:  0084ff #D60207 #FD6E8A
  secondary-dark: 534344 #A2122F
  link-color: BDAFAF
  alternate: fff

#scrollable sections 
learn-section-title: Learn More
work-section-title: How It Works
phone-section-title: Features
join-section-title: Join Us
contact-section-title: Contact Us

privacy-url: /privacy/
conditions-url: /terms-and-conditions/
advertisers-url: /contact-us/advertisers/

#hrefs
hrefs:
  first: page-top
  second: how-it-works 
  third: learn-more
  fourth: features
  last: join-us

contact-header: contact-us

#carousel background images
background:
  first: img/portfolio/bg1.jpg
  second: img/portfolio/bg2.jpg
  third: img/portfolio/bg3.jpg
  fourth: img/portfolio/bg.jpg
  phone: img/iphone.png

about:
  first: img/coin.png
  second: img/coin.png
  third: img/coin.png

# Footer settings
footer:
  copyright: Poptalk Inc. 
  location: Location
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/poptalk
  - title: facebook
    url: https://www.facebook.com/poptalk

# Postal address (add as many lines as necessary)
address:
  - line: 8390 Lyndon B Johnson Fwy
  - line: Dallas, TX 75243


# Handle Reading Markdown
markdown_ext: "markdown,mkdown,mkdn,md"

# Build settings
markdown: kramdown
permalink: pretty

defaults: 
  - scope:
      path: "privacy"
    values:
      layout: "default"
      type: "pages"
  - scope:
      path: "terms-and-conditions"
    values:
      layout: "page-layout"
      type: "pages"

exclude: ['node_modules','gulp','package.json','gulpfile.js']

